AWSTemplateFormatVersion: "2010-09-09"
Description: "HETIC AWS CloudFormation Template"

Resources:
  HeticAWSCloudFormationEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-03eb7a5d774d59f31"
      InstanceType: "t2.micro"
      Tags:
        - Key: "Name"
          Value: "hetic-aws-cloud-formation-ec2"

  HeticAWSCloudFormationS3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "hetic-aws-cloud-formation-s3"
      Tags:
        - Key: "Name"
          Value: "hetic-aws-cloud-formation-s3"
